glslc vert_standard.vert -o vert_standard.spv
glslc vert_menu_screen.vert -o vert_menu_screen.spv
glslc vert_shadow_map.vert -o vert_shadow_map.spv
glslc vert_reflect_map.vert -o vert_reflect_map.spv
glslc vert_box_internals.vert -o vert_box_internals.spv
glslc vert_darken.vert -o vert_darken.spv
glslc vert_standard_tex_coord.vert -o vert_standard_tex_coord.spv
glslc vert_standard_light_index.vert -o vert_standard_light_index.spv
glslc vert_text.vert -o vert_text.spv
glslc frag_pause_screen.frag -o frag_pause_screen.spv
glslc frag_death_screen.frag -o frag_death_screen.spv
glslc frag_red.frag -o frag_red.spv
glslc frag_red_reflect.frag -o frag_red_reflect.spv
glslc frag_blue.frag -o frag_blue.spv
glslc frag_box_internals.frag -o frag_box_internals.spv
glslc frag_empty.frag -o frag_empty.spv
glslc frag_darken.frag -o frag_darken.spv
glslc frag_volume.frag -o frag_volume.spv
glslc frag_yellow.frag -o frag_yellow.spv
glslc frag_yellow_reflect.frag -o frag_yellow_reflect.spv
glslc frag_text.frag -o frag_text.spv
