*PATH_TO_glglc*/glslc.exe vert_standard.vert -o vert_standard.spv
*PATH_TO_glglc*/glslc.exe vert_menu_screen.vert -o vert_menu_screen.spv
*PATH_TO_glglc*/glslc.exe vert_shadow_map.vert -o vert_shadow_map.spv
*PATH_TO_glglc*/glslc.exe vert_reflect_map.vert -o vert_reflect_map.spv
*PATH_TO_glglc*/glslc.exe vert_box_internals.vert -o vert_box_internals.spv
*PATH_TO_glglc*/glslc.exe vert_darken.vert -o vert_darken.spv
*PATH_TO_glglc*/glslc.exe vert_standard_tex_coord.vert -o vert_standard_tex_coord.spv
*PATH_TO_glglc*/glslc.exe vert_standard_light_index.vert -o vert_standard_light_index.spv
*PATH_TO_glglc*/glslc.exe vert_text.vert -o vert_text.spv
*PATH_TO_glglc*/glslc.exe frag_pause_screen.frag -o frag_pause_screen.spv
*PATH_TO_glglc*/glslc.exe frag_death_screen.frag -o frag_death_screen.spv
*PATH_TO_glglc*/glslc.exe frag_red.frag -o frag_red.spv
*PATH_TO_glglc*/glslc.exe frag_red_reflect.frag -o frag_red_reflect.spv
*PATH_TO_glglc*/glslc.exe frag_blue.frag -o frag_blue.spv
*PATH_TO_glglc*/glslc.exe frag_box_internals.frag -o frag_box_internals.spv
*PATH_TO_glglc*/glslc.exe frag_empty.frag -o frag_empty.spv
*PATH_TO_glglc*/glslc.exe frag_darken.frag -o frag_darken.spv
*PATH_TO_glglc*/glslc.exe frag_volume.frag -o frag_volume.spv
*PATH_TO_glglc*/glslc.exe frag_yellow.frag -o frag_yellow.spv
*PATH_TO_glglc*/glslc.exe frag_yellow_reflect.frag -o frag_yellow_reflect.spv
*PATH_TO_glglc*/glslc.exe frag_text.frag -o frag_text.spv
pause
